// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "account.find", input: string, result: AccountDetailsWithCode } | 
        { key: "account.list", input: ListArgs, result: AccountDetails[] } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "authentication.login", input: LoginArgs, result: AuthResponse } | 
        { key: "authentication.refresh_token", input: string, result: AuthResponse },
    subscriptions: never
};

export type AccountDetailsWithCode = { id: string; issuer: string; username: string; code: string }

export type AccountDetails = { id: string; issuer: string; username: string }

export type LoginArgs = { username: string; password: string }

export type AuthResponse = { access_token: string | null; refresh_token: string | null; success: boolean }

export type ListArgs<> = null
